mateusjunges/laravel-kafka

CHANGELOG.md, README.md, src/Config/Config.php, src/Config/Sasl.php, src/Contracts/CanProduceMessages.php, src/Producers/ProducerBuilder.php, src/Support/Testing/Fakes/ProducerBuilderFake.php, tests/Config/ConfigTest.php
This PR adds SASL authentication to producers.
=> Adds sasl to producer builder

CHANGELOG.md, README.md, src/Facades/Kafka.php, src/Support/Testing/Fakes/KafkaFake.php, tests/KafkaFakeTest.php
- Make message argument optional on `assertPublished` and `assertPublishedOn` methods
- Added `assertPublishedTimes` and `assertPublishedOnTimes` methods
=> Added assertion methods + message is optional argument when testing.

src/Support/Testing/Fakes/KafkaFake.php, src/Support/Testing/Fakes/ProducerBuilderFake.php, src/Support/Testing/Fakes/ProducerFake.php, tests/KafkaFakeTest.php
=> fixes for #22

src/Contracts/RetryStrategy.php, src/Handlers/RetryStrategies/DefaultRetryStrategy.php, src/Handlers/RetryableHandler.php, src/Retryable.php, tests/FailingHandler.php, tests/Handlers/RetryableHandlerTest.php
* Add RetryableHandler
This handler can retry message handling and blocks processing any other messages.
* Add docblocks to `RetryStrategy` interface
=> [1.4.x] Add RetryableHandler (#37)

.github/workflows/run-tests.yml, README.md, src/Console/Commands/KafkaConsumer/Options.php, src/Console/Commands/KafkaConsumerCommand.php, src/Consumers/CallableConsumer.php, src/Consumers/Consumer.php, src/Providers/LaravelKafkaServiceProvider.php, tests/Console/Consumers/KafkaConsumerCommandTest.php, tests/Console/Consumers/OptionsTest.php
This PR should Fix #32. Still a work in progress.
=> [1.5.X] WIP: Fix consumer command

.github/workflows/run-tests.yml, README.md, config/kafka.php, src/Console/Commands/KafkaConsumer/Options.php, src/Console/Commands/KafkaConsumerCommand.php, src/Providers/LaravelKafkaServiceProvider.php, tests/Console/Consumers/KafkaConsumerCommandTest.php, tests/Console/Consumers/OptionsTest.php
This PR adds fixes from v1.5.x to v2.0
=> [2.x] cherry pick #5c5c83c48 from v1.5.x

CHANGELOG.md, src/Console/Commands/KafkaConsumer/Options.php
=> [v1.7.x] Added SASL Security Protocol to `getSasl` method

src/Support/Testing/Fakes/ConsumerBuilderFake.php, src/Support/Testing/Fakes/ConsumerFake.php, tests/KafkaFakeTest.php
Hey @mateusjunges, support for batches was missing, I added 2 tests, one with a single batch, and another with 3 batches, I await your comments.
=> [v1.7.x] Add Batch Support for Message consumer Mock

src/Config/Config.php, src/Consumers/Consumer.php, src/Consumers/ConsumerBuilder.php, tests/Consumers/ConsumerBuilderTest.php
Hi, I really miss such a function, so I decided to try to implement it myself. I am waiting for an answer to how much this option is correct and whether it will be added to the package.
=> [v1.7.x] Additional option to stop consumer after last message on topic

src/Console/Commands/KafkaConsumerCommand.php
Resolve consumer using Laravel service container, so that, dependencies can be injected in consumer class.
=> [v1.8.x] Resolve consumer via service container

src/Config/Config.php
=> Fix compression type to be read from config file

config/kafka.php, src/Consumers/Consumer.php
=> Make consumer timeout configurable (fixes #132)

docs/consuming-messages/9-class-structure.md, docs/testing/7-mocking-your-kafka-consumer.md
=> [v1.8.x] Fix docs

composer.json, src/Concerns/InteractsWithConfigCallbacks.php, src/Config/Config.php, src/Consumers/Consumer.php, src/Consumers/ConsumerBuilder.php, src/Contracts/CanProduceMessages.php, src/Contracts/ConsumerBuilder.php, src/Contracts/InteractsWithConfigCallbacks.php, src/Contracts/KafkaConsumerMessage.php, src/Contracts/KafkaMessage.php, src/Producers/Producer.php, src/Producers/ProducerBuilder.php, src/Support/Testing/Fakes/ConsumerBuilderFake.php, src/Support/Testing/Fakes/ProducerBuilderFake.php
=> [v1.8.x] Add methods to configure config callbacks

src/Contracts/CanConsumeMessagesFromKafka.php, src/Contracts/CanPublishMessagesToKafka.php, src/Kafka.php, src/Providers/LaravelKafkaServiceProvider.php
Bind CanPublishMessagesToKafka and CanConsumeMessagesFromKafka interface with Kafka to allow dependency injection usage
=> Make Kafka class usable through interface injection

composer.json
I would like to start testing my laravel 10 migration, and currently this is the only package that blocks me in testing.
=> Add support for Laravel v10.x

src/Commit/DefaultCommitterFactory.php, tests/Commit/CommitterFactoryTest.php
The logic for creating the correct commiter depending on wheter the auto commit was on/off was wrong.
This PR fix it.
=> Fix auto commit

tests/Commit/BatchCommitterTest.php, tests/Commit/CommitterFactoryTest.php, tests/Commit/KafkaCommitterTest.php, tests/Commit/RetryableCommitterTest.php, tests/Commit/SeekToCurrentErrorCommitterTest.php, tests/Config/ConfigTest.php, tests/Config/SaslTest.php, tests/Console/Consumers/KafkaConsumerCommandTest.php, tests/Console/Consumers/OptionsTest.php, tests/Consumers/CallableConsumerTest.php, tests/Consumers/ConsumerBuilderTest.php, tests/Consumers/ConsumerTest.php, tests/FailingCommitter.php, tests/FailingHandler.php, tests/Fakes/FakeConsumer.php, tests/Fakes/FakeHandler.php, tests/Fakes/FakeSleeper.php, tests/Handlers/RetryableHandlerTest.php, tests/KafkaFakeTest.php, tests/KafkaTest.php, tests/LaravelKafkaTestCase.php, tests/Message/Deserializers/AvroDeserializerTest.php, tests/Message/Deserializers/JsonDeserializerTest.php, tests/Message/KafkaAvroSchemaTest.php, tests/Message/MessageTest.php, tests/Message/Registry/AvroSchemaRegistryTest.php, tests/Message/Serializers/AvroSerializerTest.php, tests/Message/Serializers/JsonSerializerTest.php, tests/Producers/ProducerTest.php
This PR makes all test classes final and add missing return types to tests methods.
=> Add missing return types

docs/consuming-messages/5-configuring-consumer-options.md, src/Config/Config.php, src/Console/Commands/KafkaConsumer/Options.php, src/Console/Commands/KafkaConsumerCommand.php, src/Consumers/Consumer.php, src/Consumers/ConsumerBuilder.php, src/Contracts/ConsumerBuilder.php, src/Support/InfiniteTimer.php, tests/Consumers/ConsumerTest.php
add logic to stop a consumer after a specific time
=> Add logic to stop a consumer after a number of seconds

src/Producers/Builder.php, tests/KafkaTest.php
=> Do not require to specify message topic twice

src/Concerns/HandleConsumedMessage.php, src/Concerns/PrepareMiddlewares.php
=> Consumer middlewares work as expected

composer.json, src/AbstractMessage.php, src/Contracts/ProducerMessage.php, src/Message/Message.php
=> Allow to use keys other than strings

config/kafka.php, src/Config/Config.php, src/Contracts/MessageProducer.php, src/Producers/Builder.php, src/Producers/Producer.php, src/Support/Testing/Fakes/ProducerBuilderFake.php
=> Allow to customize flush settings (retries + timeout)

.github/workflows/run-tests.yml, composer.json
Run package tests against PHP 8.4
=> Add php 8.4 to tests workflow

src/Commit/RetryableCommitter.php
=> Add rebalance in progress to retryable errors

src/Support/Testing/Fakes/KafkaFake.php, tests/KafkaFakeTest.php
fixes #339 
@mateusjunges I'll leave it up to you to write a test for this or not. I could confirm this fixes my issue
=> fix: Implement publishAsync on KafkaFake

src/Consumers/Builder.php, src/Contracts/MessageProducer.php, src/Producers/Builder.php, src/Support/Testing/Fakes/BuilderFake.php, src/Support/Testing/Fakes/KafkaFake.php, src/Support/Testing/Fakes/ProducerBuilderFake.php
=> Fix deprecation warnings
