mateusjunges/laravel-kafka

README.md
Hi, great lib, I found some typos when read you documentation and this is the fix.
=> Documentation Typos

src/Support/Testing/Fakes/KafkaFake.php, src/Support/Testing/Fakes/ProducerBuilderFake.php, src/Support/Testing/Fakes/ProducerFake.php, tests/KafkaFakeTest.php
This PR originally was to fix incorrect testing code in `src/Support/Testing/Fakes/KafkaFake.php`
Previously this code, the `published` method was running the callback against the `$message` variable that was actually passed in during the test definition. This made no sense as the filter ran on the same object everytime so wasn't actually performing a truthy check on the messages that were actually dispatched.
```php
private function published(KafkaProducerMessage $message = null, $callback = null): Collection
{
if (! $this->hasPublished()) {
return collect();
}
$callback = $callback ?: function () {
return true;
};
return collect($this->getPublishedMessages())->filter(function ($_, $topic) use ($message, $callback) {
return $callback($message, $topic);
});
}
```
I reworked this to …
=> Reworked testing framework so that it properly checks what was dispatched

README.md, src/Consumers/Consumer.php, src/MessageCounter.php, tests/Consumers/ConsumerTest.php, tests/LaravelKafkaTestCase.php
We were looking at adding graceful shutdown to the library as we use it inside k8s and we are currently unable to stop kafka consumers without killing the container.
Hopefully this should help for anyone in a similar situation.
=> [1.4.x] Added graceful shutdown function to consumers

README.md, src/Consumers/Consumer.php, tests/Message/Deserializers/AvroDeserializerTest.php, tests/Message/Deserializers/JsonDeserializerTest.php, tests/Message/Serializers/AvroSerializerTest.php, tests/Message/Serializers/JsonSerializerTest.php
Some references to the encode/decode terminology were still in the (public) API's of the lib, so I did some cleaning.
I didn't change `AvroEncoderException` (yet) because that will break backwards compatibility. What's your take on that @mateusjunges?
=> Improve consistency on encode/serialize terms

README.md, src/Commit/BatchCommitter.php, src/Commit/Contracts/Committer.php, src/Commit/Contracts/CommitterFactory.php, src/Commit/DefaultCommitterFactory.php, src/Commit/KafkaCommitter.php, src/Commit/RetryableCommitter.php, src/Commit/SeekToCurrentErrorCommitter.php, src/Commit/VoidCommitter.php, src/Consumers/Consumer.php, src/Consumers/ConsumerBuilder.php, tests/Commit/BatchCommitterTest.php, tests/Commit/CommitterFactoryTest.php, tests/Commit/KafkaCommitterTest.php, tests/Commit/RetryableCommitterTest.php, tests/Commit/SeekToCurrentErrorCommitterTest.php, tests/Consumers/ConsumerBuilderTest.php, tests/Consumers/ConsumerTest.php, tests/FailingCommitter.php
Before it was not possible to add custom committers or custom committer configuration to the consumer, so here is a proposal to add support.
Creating the committers in the consume method instead of injecting via the constructor of `Consumer` makes sense because in some cases you want the `RdKafka\KafkaConsumer` object in the committer. Like the `KafkaCommitter` that was present already, and the `SeekToCurrentErrorCommitter` also needs it.
Hence the extraction of a `CommitterFactory` interface and renaming the `CommitterFactory` class to `DefaultCommitterFactory`.
I've also added the `SeekToCurrentErrorCommitter`, for which I started these changes in the first place. You can use this committer when you need to do in-order processing of messages while blocking the entire stream consumption …
=> Add message context to Committers

src/Contracts/RetryStrategy.php, src/Handlers/RetryStrategies/DefaultRetryStrategy.php, src/Handlers/RetryableHandler.php, src/Retryable.php, tests/FailingHandler.php, tests/Handlers/RetryableHandlerTest.php
This handler can retry message handling and blocks processing any other messages.
This is helpful when you want to process messages in-order, or want to retry handling before sending the message to the DLQ.
I've also made the `Retryable::$retryableErrors` setting nullable, allowing retries for any exception.
**Example usage:**
```php
$handler = function(KafkaConsumerMessage $message) {
Log::debug('Received message:', ['message' => $message->getBody()]);
throw new \RuntimeException('test');
};
$retryableHandler = new RetryableHandler($handler, new DefaultRetryStrategy(), new NativeSleeper());
$kafkaConsumer = Kafka::createConsumer()
->withHandler($retryableHandler)
->build();
```
This would retry to handle the message 6 times. After that it is recognised as failed by the exception …
=> [1.4.x] Add RetryableHandler

src/Exceptions/LaravelKafkaException.php, src/Exceptions/SchemaRegistryException.php, src/Exceptions/Serializers/AvroSerializerException.php, src/Message/Serializers/AvroSerializer.php, tests/Message/Serializers/AvroSerializerTest.php
Renamed the Avro exception as mentioned in https://github.com/mateusjunges/laravel-kafka/pull/31#issuecomment-982725715.
Also, this PR lets all exceptions extend from the base `LaravelKafkaException`, which is now `abstract`.
**Backwards compatibility breaks:**
- `Junges\Kafka\Exceptions\Encoders\AvroEncoderException` is renamed to `Junges\Kafka\Exceptions\Serializers\AvroSerializerException`
As you mentioned @mateusjunges, this change is pending for the next minor version.
=> [1.5.x] Small exception improvements

CHANGELOG.md, README.md, src/Config/Config.php, src/Consumers/ConsumerBuilder.php, tests/Consumers/ConsumerBuilderTest.php
This PR adds a `withBrokers` setter to the Consumer API.
It also makes the `withAutoCommit` accept a `bool` argument to set the `auto_commit` to false, so instead of doing 
```php 
$consumer = Kafka::createConsumer(brokers: $config['brokers']);
if ($config['auto_commit']) {
$consumer->withAutoCommit();
}
``` 
you can do 
```php
$consumer = Kafka::createConsumer(brokers: $config['brokers'])->withAutoCommit($config['auto_commit']);
```
I've fixed `getConsumerOptions` to use correct `auto_commit` option and fixed the `auto_commit` option in the initial Consumer options array, to be casted to string.
=> [1.5.x] Consumer API improvements

src/Producers/Producer.php, tests/KafkaTest.php
This PR adds support for librdkafka under v0.11.4, which does not support the usage of `producev` method and fix some mocks in tests.
=> [1.5.x] Adds support for `librdkafka` v0.11.3

.github/workflows/run-tests.yml, Makefile, build/test/Dockerfile, dev/Dockerfile, docker-compose-test.yaml
This PR adds PHP 8.1 support and replaces the current docker image used for tests.
=> [2.x] Replace test docker image + PHP 8.1 support

src/Config/Config.php, tests/Config/ConfigTest.php
This is a fix for a bug found while implementing a SASL/SCRAM consumer. The `getConsumerOptions` method didn't include the SASL options.
I found some other small things which I haven't had the time to make a PR for / give as feedback for https://github.com/mateusjunges/laravel-kafka/pull/45. Also some bigger things, for example a refactor of the consumer/producer and related builders to improve extension and mocking abilities.
I wish to free up some time to work on this project, but not expecting much the coming 1-2 weeks.
=> [1.5.x] Include SASL on consumer config when applicable

CHANGELOG.md, src/Config/Config.php, tests/Config/ConfigTest.php
This PR fixes #69, allowing to use SASL with lower and uppercase config keys.
=> [1.6.x] Fixes #69 - Allow to use SASL with lowercase config keys

src/Config/Config.php, tests/Config/ConfigTest.php
This PR removes the `compression.codec` configuration option from the consumer configuration. Fixes #75
=> Remove producer config property from `getConsumerOptions` method

src/Config/Config.php, src/Consumers/Consumer.php, src/Producers/ProducerBuilder.php
This PR passes the `securityProtocol` key to the config class when using sasl. Should fix #77
=> [v1.6.x] Fix sasl authentication

src/Config/Config.php
This PR adds the missing `auto.offset.reset` config options to the consumer only options array
=> [1.6.x] Add `auto.offset.reset` as consumer only config option

src/Console/Commands/KafkaConsumerCommand.php
=> [1.6.x] Use correct consumer group id config key

src/Producers/Producer.php, tests/LaravelKafkaTestCase.php, tests/Producers/ProducerTest.php
1.6 variant of: https://github.com/mateusjunges/laravel-kafka/pull/91
Hey Mateus 👋 - I've had to do a bit of funkiness to get around how we're mocking this to get the producer class available to test appropriately. Please let me know if you have ideas on how to do this a bit cleaner 😊
=> [1.6.x] Fix serialize

CHANGELOG.md, docs/consuming-messages/5-configuring-consumer-options.md, src/Consumers/ConsumerBuilder.php, src/Exceptions/KafkaConsumerException.php, tests/Consumers/ConsumerBuilderTest.php
This PR fixes the undefined offset 0 error thrown when trying to set a DLQ without suscribing to any kafka topics.
=> [v1.7.x] do not allow setting dlq without subscribing to topics

README.md
Hi :) I really suffer from it, when I come to the documentation page via link in repository 😂
=> [v1.7.x] Link to the current version documentation fixed

src/Consumers/ConsumerBuilder.php, tests/Consumers/ConsumerBuilderTest.php
Hi, I'm testing the package with a Sasl connection and in the consumer builder, when the securityProtocol setting is specified, argument 4 of the Sasl class is not taken into account, so the only way to make it work is to use the withSecurityProtocol. method, this PR solves the problem
=> [v1.7.x] Fix securityProtocol sasl config in consumer

dev/Dockerfile
The image `mateusjunges/laravel:8.0-v1.5.3-5.0.0-8` no longer exists
=> [v1.7.x] Fix docker file

src/Consumers/Consumer.php
This PR fixes #120 by adding a check for `RD_KAFKA_RESP_ERR__TIMED_OUT` when the topic has no more messages and then stop consuming.
=> Fixes #120

src/Config/Config.php, src/Console/Commands/KafkaRestartConsumersCommand.php, src/Consumers/Consumer.php, src/Providers/LaravelKafkaServiceProvider.php, tests/Consumers/ConsumerTest.php
This is a proposal to have the possibility to restart consumer processes by means of an Artisan command
- New comand `kafka:restart-consumers`  
When this command is executed, a key cache called `laravel-kafka:consumer:restart` is created with the current date in timestamp format, the kafka process checks the cache every 1 second (you can define the interval in milliseconds in the `Config` class), when the timestamp is different from the last restart the loop stops.
Feel free to send your suggestions
=> [v1.8.x] Add restart command

build/laravel-kernels/kernel.php, build/test/Dockerfile, dev/Dockerfile, dev/laravel-console-kernel.php
=> [v1.8.x] Use dummy world instead of laravel namespace in dev classes

src/Config/Config.php
This PR fixes the filter for producer and consumer only config options, avoiding the following logs:
```
%4|1667415046.254|CONFWARN|rdkafka#producer-2| [thrd:app]: Configuration property auto.offset.reset is a consumer property and will be ignored by this producer instance
```
=> Filter config options for consumer and producers

config/kafka.php, src/Producers/Producer.php
This PR adds new config option `kafka.flush_retry_sleep_in_ms` that you can use to configure how much time the producer should sleep before retrying to flush.
fixes #155
=> Allow to configure sleep timeout on flush retry

src/Consumers/Consumer.php
When consuming messages, if a custom exception is thrown, it just logs the error to the output and then `returns false`, since there might be some reporting methods available on the custom exception, this causes Laravel default exception handling not to work, so I just used `report()` helper on the exception.
=> report the exception on consuming messages

CHANGELOG.md, composer.json, docs/6-upgrade-guide.md, docs/advanced-usage/2-graceful-shutdown.md, docs/consuming-messages/4-message-handlers.md, src/Consumers/CallableConsumer.php, src/Consumers/Consumer.php, src/Consumers/ConsumerBuilder.php, src/Contracts/CanConsumeMessages.php, src/Support/Testing/Fakes/ConsumerFake.php, tests/Consumers/ConsumerTest.php, tests/Handlers/RetryableHandlerTest.php, tests/KafkaFakeTest.php, tests/LaravelKafkaTestCase.php
This PR adds the ability to consumers to subscribe to `SIGQUIT` and `SIGTERM` singals, stopping the consumer whenever one of these signals are received. In order to use it, you must have the `pcnt` extension loaded in your environment.
=> Allow consumer to subscribe to signals

src/Producers/MessageBatch.php, src/Support/Testing/Fakes/ProducerFake.php, tests/KafkaFakeTest.php
=> Allow assertPublishedOnTimes to be used with batch messages

docs/consuming-messages/10-queueable-handlers.md, src/Concerns/HandleConsumedMessage.php, src/Concerns/PrepareMiddlewares.php, src/Consumers/CallableConsumer.php, src/Consumers/ConsumerBuilder.php, src/Consumers/DispatchQueuedHandler.php, src/Contracts/Handler.php, src/Contracts/Middleware.php, src/Support/Testing/Fakes/ConsumerBuilderFake.php, tests/Consumers/CallableConsumerTest.php, tests/Consumers/ConsumerTest.php, tests/Consumers/SimpleQueueableHandler.php
This PR adds the ability to delay the execution of your message handlers by dispatching a job to the queue.
To create a queueable message handler, you just need to implement the `ShouldQueue` and the `\Junges\Kafka\Contracts\Handler\  interfaces:
```php
use Junges\Kafka\Contracts\Handler as HandlerContract;
class Handler implements HandlerContract, ShouldQueue
{
public function __invoke(KafkaConsumerMessage $message): void
{
// Handle the consumed message.
}
}
```
=> [2.x] Allow to queue message handlers

config/kafka.php, dev/kafka.php, docs/3-installation-and-setup.md, src/Console/Commands/KafkaRestartConsumersCommand.php, src/Consumers/Consumer.php, tests/LaravelKafkaTestCase.php
In case you don't want to use the same cache driver as the application.
I think the test "testItCanRestartConsumer()" cover the modification, let me know if it's not enough.
=> Add the ability to change the cache driver

README.md
Hey, I updated the README file, so the documentation link is pointing to 1.13 documentation, instead of 1.8 one.
=> Update README.md to link to the 1.13 documentation page

src/Kafka.php, tests/KafkaTest.php
In order to make use of macros the Illuminate Macroable trait has been added to Junges\Kafka\Kafka.
An example could look like this:
```php
$sasl = new Sasl(username: 'username', password: 'password', mechanisms: 'mechanisms');
Kafka::macro('defaultProducer', function (string $topic) use ($sasl) {
return $this->publishOn($topic)->withSasl($sasl);
});
$producer = Kafka::defaultProducer('test-topic');
```
=> Make Kafka macroable

config/kafka.php, src/Console/Commands/KafkaConsumer/Options.php, src/Console/Commands/KafkaConsumerCommand.php
Hi @mateusjunges 
When runing:
```cli
php artisan kafka:consume --topics=my-topic --consumer="\\App\\Consumers\\MyConsumer"
```
I takes settings from `config`, but `securityProtocol` is ommited, so you have to explicity pass it `--securityProtocol=SASL_SSL`.
=> Fixed default securityProtocol config

CHANGELOG.md, docs/3-installation-and-setup.md, docs/advanced-usage/2-graceful-shutdown.md, docs/consuming-messages/10-class-structure.md, docs/consuming-messages/11-queueable-handlers.md, docs/consuming-messages/3-assigning-partitions.md, docs/consuming-messages/4-consumer-groups.md, docs/consuming-messages/5-message-handlers.md, docs/consuming-messages/6-configuring-consumer-options.md, docs/consuming-messages/7-custom-deserializers.md, docs/consuming-messages/8-consuming-messages.md, docs/consuming-messages/9-handling-message-batch.md, src/Config/Config.php, src/Consumers/Consumer.php, src/Consumers/ConsumerBuilder.php
Kafka Clients allows you to implement your own partition assignment strategies for consumers.
This PR allows to specify which partitions a consumer should consume from.
In the following example, this consumer will only consume messages from the `my-awesome-topic` partitions `2`, and `3`. Messages from any other partition won't be handled by this consumer.
```php
Kafka::createConsumer()
->assignPartitions([
new TopicPartition('my-awesome-topic', 2),
new TopicPartition('my-awesome-topic', 3),
])
->withHandler(function (ConsumedMessage $message) {
// Handle the message here
})->build();
$consumer->consume();
```
=> [v2.x] Partition assignment

src/Facades/Kafka.php, src/Support/Testing/Fakes/KafkaFake.php, tests/KafkaFakeTest.php
This is the version of #246 but for v1.13.x
=> [v1.13.x] Passthru missing methods on KafkaFake for macro accessibility

src/Contracts/KafkaManager.php, src/Facades/Kafka.php, src/Kafka.php, src/Providers/LaravelKafkaServiceProvider.php, src/Support/Testing/Fakes/KafkaFake.php, tests/KafkaFakeTest.php
This PR implements `ForwardCalls` trait onto the `KafkaFake` class so that macro'd methods are still accessible after calling `Kafka::fake()`
=> Passthru missing methods on `KafkaFake` for macro accessibility

src/Facades/Kafka.php, src/Kafka.php, src/Support/Testing/Fakes/KafkaFake.php, src/Support/Testing/Fakes/ProducerFake.php, tests/KafkaTest.php
Follow up on #247. Should fix #245
=> Fix passthru of missing methods to root

docs/6-upgrade-guide.md, docs/advanced-usage/2-graceful-shutdown.md, docs/advanced-usage/6-stopping-a-consumer.md, docs/consuming-messages/10-class-structure.md, docs/consuming-messages/11-queueable-handlers.md, docs/consuming-messages/5-message-handlers.md, docs/consuming-messages/9-handling-message-batch.md, src/Concerns/HandleConsumedMessage.php, src/Config/Config.php, src/Consumers/Builder.php, src/Consumers/CallableBatchConsumer.php, src/Consumers/CallableConsumer.php, src/Consumers/Consumer.php, src/Consumers/DispatchQueuedHandler.php, src/Consumers/NullBatchConsumer.php, src/Contracts/BatchMessageConsumer.php, src/Contracts/Consumer.php, src/Contracts/ConsumerBuilder.php, src/Contracts/MessageConsumer.php, src/Support/Testing/Fakes/BuilderFake.php, src/Support/Testing/Fakes/ConsumerFake.php, tests/Consumers/CallableConsumerTest.php, tests/Consumers/ConsumerTest.php, tests/Fakes/FakeHandler.php, tests/KafkaFakeTest.php
This PR moves the call to set a `onStopConsuming` callback to the Consumer Builder instance instead of the consumer. Previously, you had to create the consumer calling `build` before setting the `onStopConsuming` callback. This PR makes it possible to set it while building your consumer.
Also, an instance of `MessageConsumer` is now passed to your handler functions, so it's easier to stop consuming messages.
=> Set `onStopConsuming` while building consumer and make `MessageConsumer` accessible to handler functions

src/Contracts/Manager.php, src/Factory.php, src/Support/Testing/Fakes/KafkaFake.php, tests/Consumers/ConsumerTest.php
This PR allows macroed consumers to be tested. 
Since macro calls are forwared to the actual kafka manager instance instead of the fake implementation, that class had no access to the mocked messages.
=> Allow to test macroed consumers

src/Config/Config.php, src/Console/Commands/KafkaConsumer/Options.php
I changed 'commit' in all places to be an int with a default of 1 so that type errors no longer occur.
CONTEXT:
I get this error when trying to consume messages using this command:
command: php vendor/bin/sail artisan kafka:consume --consumer=App\Commands\Consumers\Kafka\MyConsumer --topics=my_topic --groupId=my_group --maxMessage=5000 --maxTime=3600
error: Junges\Kafka\Config\Config::getCommit(): Return value must be of type int, string returned.
The value of commit is "1".
=> Fixed type errors caused by `commit` having an irregular type

src/Support/Testing/Fakes/ProducerBuilderFake.php, tests/KafkaFakeTest.php
After the last fix introduced here: https://github.com/mateusjunges/laravel-kafka/pull/270
the logic was not copied also at the `ProducerBuilderFake` causing fake producer not to publish messages for the correct topics.
Now even if we pass the message details using the publisher methods or even if we do this using the `withMessage` function, the tests will operate correctly.
Cheers!
=> Mirror logic to enable fake builder set the topic name for all the messages at once

src/Consumers/Builder.php
The purpose of this change was to allow the consumer to be created in lumen.
I had tried to create a consumer in Lumen but it failed with the error:
`Call to undefined function resolve()`
And because `resolve()` function is defined as:
```
if (! function_exists('resolve')) {
/**
* Resolve a service from the container.
*
* @param  string  $name
* @param  array  $parameters
* @return mixed
*/
function resolve($name, array $parameters = [])
{
return app($name, $parameters);
}
}
```
Thus we could safely replace the change with `app()` helper and it would help us in using this awesome package with Laravel.
Please review.
=> Replaced resolve helper with app to facilitate use for lumen

src/Consumers/Consumer.php
When cache driver is Redis and you retrieve a value from the store, it's automatically string type because of how Redis retrieves these values. Even if key "laravel-kafka:consumer:restart" is stored as an integer on RestartConsumersCommand, when retrieving, Redis will return that as a string.
The problem is the combination of strict_types=1 and type hinting. PHP can't automatically convert that to an integer, so there is a type error exception.
On this PR we cast the result of getLastRestart, so it's always an integer.
=> Add int casting to getLastRestart method

src/Commit/RetryableCommitter.php
This PR marks the `RD_KAFKA_RESP_ERR_ILLEGAL_GENERATION` error as retryable as an attempt to fix #295
=> Attempt to fix invalid group id generation

docs/producing-messages/1-producing-messages.md, src/Facades/Kafka.php, src/Factory.php, src/Producers/Builder.php, src/Producers/Producer.php
See discussion https://github.com/mateusjunges/laravel-kafka/discussions/309
=> Introduce Kafka::asyncPublish() that will not flush on each send/batchSend but only once when the application is terminating

docs/producing-messages/6-producing-message-batch-to-kafka.md, src/Producers/Producer.php, tests/KafkaTest.php
Currently, when sending batch messages, if a message in the batch specifies a topic, it is overwritten when the batch is being produced. This PR fixes this behavior.
Fix #308
=> Do not override topic when publishing batch messages

docs/producing-messages/1-producing-messages.md, src/Contracts/Manager.php, src/Facades/Kafka.php, src/Factory.php
This PR adds the `fresh` method, which allows you to reset the Kafka manager instance.
=> Allow to reset the Kafka Manager

src/Commit/RetryableCommitter.php
This issue was fixed in #305 , but it is currently not updated for 1.13.x versions. We are having the same issue and cannot upgrade to 2.x yet. This PR will help systems running on 1.13.x to automatically retry when encountering the "Invalid group id generation" error
=> Fix invalid group id generation for v1.13.x

src/Contracts/MessageProducer.php, src/Producers/Builder.php, src/Support/Testing/Fakes/ProducerBuilderFake.php
Adds in the ability to set complete body of the produced message w/out having to completely replace the message via ->withMessage()
=> Adds in the ability to set complete body when producing messages

src/Consumers/Consumer.php
If **KAFKA_CONSUMER_DEFAULT_TIMEOUT** is configured in the **.env** file, it will result in an error `RdKafka\KafkaConsumer::consume(): Argument #1 ($timeout_ms) must be of type int, string given`
=> Convert `KAFKA_CONSUMER_DEFAULT_TIMEOUT` to an integer to avoid type error

config/kafka.php
Laravel 11 changed new cache env key. 
This PR make use of specific kafka driver config, then laravel 10 key, then laravel 11 key, in order to find. 
Laravel 10 - https://github.com/laravel/laravel/blob/7effeb99ec1568f006ed95e60d3e7dfeed1b8160/config/cache.php#L18
Laravel 11 - https://github.com/laravel/laravel/blob/70f437b6fc7801ef11d6627d9ab48d698ffe5f26/config/cache.php#L18
=> Prefer Cache env from laravel 11

src/Producers/Producer.php
I had issues with the new async producer. Because the reference is captured in the terminate callback, in fact the rdkafka producer is never garbage collcted and because of that in the queue the connection to kafka is never terminated. 
That causes issue when used in the queue as new connections indeed created, but the old ones are never closed.
The solution would be to use the destructor. In that way - if you use the main facade method - the reference is kept around for a second publish, and if you do Kafka::fresh(), the message will be flushed when it foes out of scope and then when it is destroyed the connection is closed too. That works great for the Queue because the Facade cache is reset after each job execution! If someone wants to implement a persistent publisher that works …
=> Use destruct method to flush the producer
